### ISSUE TITLE
[BUG] Schild wird beim manuellen setzen nicht angezeigt

### ISSUE THREAD

**Issue by Greendrgon** [raidcraft/rcregions#10]
Wenn man ein Schild mit [region] setzt wird dieses nicht richtig angezeigt (es ist lehr) erst beim setzten des selben Schilds an andere Position wird das erste richtig angezeigt.

**Comment by Silthus** [comment]
> Wenn man ein Schild mit [region] setzt wird dieses nicht richtig angezeigt (es ist lehr) erst beim setzten des selben Schilds an andere Position wird das erste richtig angezeigt.

Hast du das vorher nochmal getestet? Hatte das glaube ich schon behoben.

**Comment by Silthus** [comment]
Tritt wohl immer noch auf.

**Comment by Greendrgon** [comment]
Ja
