### ISSUE TITLE
Spieler Member hinzufügen lassen

### ISSUE THREAD

**Issue by Greendrgon** [raidcraft/rcregions#12]
Eigentümer eines Grundstück müssen die Möglichkeit bekommen andere Spieler dem GS als Member hinzu zufügen.

**Comment by Silthus** [comment]
Das geht über die normalen WorldGuard Permissions und muss nicht in unser Plugin. Rechte auf dem Liveserver habe ich angepasst. Außerdem kann man in der neuesten Version leicht das WorldGuard Menü aufrufen und via Klick dann alles bequem hinzufügen.
