### ISSUE TITLE
LWC Sicherungen beim Grundstücke kauf löschen. 

### ISSUE THREAD

**Issue by Greendrgon** [raidcraft/rcregions#14]
Wenn ein Spieler ein Grundstück kauft sollen alle LWC Sicherungen entfernt werden.
Warum beim kaufen?! Weil wenn ein Spieler sein Grundstück an den Server verkauft bleiben noch seine Sicherungen auf den Kisten und er hat noch Zeit die Kisten zu räumen. Dies ist wegen den steigenden Preisen pro Grundstück ein entgegen kommen von uns damit sie erst ihr altes Grundstück verkaufen können und dann ein neues kaufen können ohne den Multiplikator für mehrere Grundstücke.

**Comment by Silthus** [comment]
Wäre sowas hier auch eine Alternative: https://github.com/pop4959/LWCX/wiki/Protection-cleanup

Also `/lwc admin cleanup`?

**Comment by Greendrgon** [comment]
Dazu müssten wir alle Kisten usw löschen.

**Comment by Silthus** [comment]
Es ist ja eh geplant, dass das GS beim Kauf zurückgesetzt wird, da verschwinden dann alle Kisten und es wird automatisch der Cleanup Befehl ausgeführt. So meine Idee.

**Comment by Silthus** [comment]
Es gibt wohl auch die Möglichkeit Protections automatisch basierend auf der Worldguard Region erstellen zu lassen: https://github.com/pop4959/LWCX/wiki/Configuration#Worldguard

Damit wären immer automatisch alle Kisten in einer Region für die Mitglieder und den Besitzer geschützt. Müsste man testen ob sich das aktualisiert wenn sich die Region ändert.

**Comment by Silthus** [comment]
Ah ich hab noch was besseres gefunden: https://github.com/pop4959/LWCX/issues/11#issuecomment-516620654

Mit dem Command können wir leicht alle Sicherungen in einem GS entfernen.

`/lwc admin purgeregion <region> <world>`
