### ISSUE TITLE
[BUG] Wenn ein GS gekauft wurde kann der Eigentüber das schild nicht entfernen

### ISSUE THREAD

**Issue by Greendrgon** [raidcraft/rcregions#29]
Bin mir nicht sicher ob das ein Bug ist oder gewollt, aber wenn das GS gekauft wurde kann man das Schild nicht abbauen.

**Comment by Silthus** [comment]
Shift + Abbauen sollte gehen. Kann es aber auch ändern dass im Survival
Mode das Schild auch ohne Shift abgebaut werden kann.

Greendrgon <notifications@github.com> schrieb am Fr. 11. Dez. 2020 um 16:04:

**Comment by Greendrgon** [comment]
entwerder das oder das eine meldung ausgeben die sagt das sie es mit shift abbauen können.
